name: test
on:
  pull_request:
  push:
    branches: ["*", "!release"]
jobs:
  test:
    name: "Perl ${{ matrix.perl }} on ${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.40", "5.36", "5.26"]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "${{ matrix.perl }}"
      - name: Install dependencies
        run: |
          cpanm -n Test::CPAN::Changes Test::Pod::Coverage Test::Pod Test::Spelling
          cpanm -n Data::Validate::Domain Data::Validate::IP YAML::LibYAML
          cpanm -n https://github.com/mojolicious/json-validator/archive/main.tar.gz
          cpanm -n --installdeps .
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j4
